name: .NET 8 CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Barber.sln

      - name: Build
        run: dotnet build Barber.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test Barber.sln --no-build --verbosity normal

      - name: Publish
        run: dotnet publish Barber.sln -c Release -o ./publish
